### ISSUE TITLE
battery drainage

### ISSUE THREAD

**Issue by sd-timaru** [michael-cheung-thebus/foreground_service#4]
Hi!
I made a small application to test this plugin and noticed that this application consumes a lot of the battery. 10% in one hour. And the phone (Samsung galaxy A5 2017 with Android 8) was really warm... ...

**Comment by weiyinqing** [comment]
Hi!
The FlutterForegroundService.stop() is bad.

**Comment by michael-cheung-thebus** [comment]
@sd-timaru Yes, a foreground service will tend to use a lot of power.  This is because it's running constantly in the foreground, so the CPU can't sleep, etc. etc.  In other words, it's meant for applications where "always-on" is the goal.

If always-on/on-demand is not the primary goal, periodic check-ins using things like background services/jobs or timers are more suitable.

@weiyinqing Please open a separate issue with more details on what you're doing.

**Comment by TheLastGimbus** [comment]
I used native Android foreground service before, and it never was getting so damn hot! I don't know how you did it, but my phone is just melting on my desk!
